#pragma once

enum ENUM_MSG_TYPE
{
    ENUM_MSG_REGISTER_UPDATE_PLAYER_REQUEST = 0,  // 人物注册及更新
    ENUM_MSG_REGISTER_UPDATE_PLAYER_RESPONSE = 1,    // 人物广播回复

    ENUM_MSG_DELETE_PLAYER_REQUEST,    // 删除人物请求（某个客户端异常下线的场景）
    ENUM_MSG_DELETE_PLAYER_RESPONSE,   // 删除人物回复

    ENUM_MSG_SYNC_PLAYERS_REQUEST,     // 同步当前在线人物列表
    ENUM_MSG_SYNC_PLAYERS_RESPONSE,    // 当前在线人物列表回复

    ENUM_MSG_SYNC_TREES_REQUEST,       // 同步树木列表
    ENUM_MSG_SYNC_TREES_RESPONSE,      // 树木列表回复

    ENUM_MSG_HIT_TREE_REQUEST,         // 砍树请求
    ENUM_MSG_HIT_TREE_RESPONSE,        // 砍树结果

    ENUM_MSG_UPDATE_TREE_PUSH,         // 树木状态推送

    ENUM_MSG_SYNC_MONSTERS_REQUEST,    // 同步怪物列表
    ENUM_MSG_SYNC_MONSTERS_RESPONSE,   // 怪物列表回复

    ENUM_MSG_HIT_MONSTER_REQUEST,      // 攻击怪物请求
    ENUM_MSG_HIT_MONSTER_RESPONSE,     // 攻击怪物结果

    ENUM_MSG_UPDATE_MONSTER_PUSH,      // 怪物状态推送

    ENUM_MSG_SYNC_DROPS_REQUEST,       // 同步掉落物列表
    ENUM_MSG_SYNC_DROPS_RESPONSE,      // 掉落物列表回复

    ENUM_MSG_PICK_DROP_REQUEST,        // 拾取掉落物请求
    ENUM_MSG_PICK_DROP_RESPONSE,       // 拾取掉落物结果

    ENUM_MSG_UPDATE_DROP_PUSH,         // 掉落物状态推送

    ENUM_MSG_SYNC_INVENTORY_REQUEST,   // 同步背包请求
    ENUM_MSG_SYNC_INVENTORY_RESPONSE,  // 背包列表回复
    ENUM_MSG_UPDATE_INVENTORY_PUSH,    // 背包状态推送

    ENUM_MSG_SYNC_PROJECTILES_REQUEST, // 同步投射物请求
    ENUM_MSG_SYNC_PROJECTILES_RESPONSE,// 投射物列表回复
    ENUM_MSG_UPDATE_PROJECTILE_PUSH,   // 投射物状态推送

    ENUM_MSG_SENDMESSAGE_REQUEST,  // 发送消息请求
    ENUM_MSG_SENDMESSAGE_RESPONSE,    // 发送消息回复
};

enum ENUM_TREE_STATE
{
    ENUM_TREE_STATE_ALIVE = 0,
    ENUM_TREE_STATE_STUMP = 1
};

enum ENUM_MONSTER_STATE
{
    ENUM_MONSTER_STATE_ALIVE = 0,
    ENUM_MONSTER_STATE_DEAD = 1
};

enum ENUM_DROP_STATE
{
    ENUM_DROP_STATE_AVAILABLE = 0,
    ENUM_DROP_STATE_PICKED = 1
};

enum ENUM_PROJECTILE_STATE
{
    ENUM_PROJECTILE_STATE_ACTIVE = 0,
    ENUM_PROJECTILE_STATE_IMPACT = 1,
    ENUM_PROJECTILE_STATE_EXPIRED = 2
};
